name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'added'
      - 'add'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'fixed'
  - title: '⚙️ Changes'
    labels:
      - 'changed'
      - 'dependencies'
      - 'update'
      - 'updated'
      - 'refactor'
      - 'refactoring'
      - 'removed'
      - 'remove'
change-template: '- $TITLE (#$NUMBER - thanks to @$AUTHOR)'
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
  patch:
    labels:
      - 'patch'
      - 'bugfix'
      - 'debt'
      - 'dependencies'
  default: patch
template: |
  ## What’s Changed

  $CHANGES